### PR TITLE
Docs fix readme

### PR DESCRIPTION
**Pull request by nemesis567**
Changing readme:
 - Without recursive option the submodule from the SDK alt-config won't be retrieved resulting in build failure.
 - resource->GetMain() returns a StringView which is not implicitly convertible to a std::string.

### CODE REVIEW

**Comment by LeonMrBonnie** [comment]
> resource->GetMain() returns a StringView which is not implicitly convertible to a std::string.

This was actually caused by the C++ SDK submodule not being updated in this repo, I have did this now, so that change is not needed anymore. (The alt::StringView and alt::String classes have been removed from the SDK some time ago)

**Comment by nemesis567** [comment]
Yes, I can confirm that after updating the sdk the StringView has been replaced with std::string. Maybe it's best to add to the readme a step to update the sdk as well, I forgot to do that.

**Comment by LeonMrBonnie** [comment]
Can you please remove the second commit from this PR so I can merge it?

**Comment by nemesis567** [comment]
I did and verify if the readme is fine.

**Pull request merged**
